with-expecter: true
dir: "mocks"
packages:
  github.com/resident-x/go-grott/internal/domain:
    config:
      filename: "{{.InterfaceName}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: mocks
    interfaces:
      DataParser:
      MessagePublisher:
      MonitoringService:
      Registry:
  github.com/eclipse/paho.mqtt.golang:
    config:
      filename: "mqtt_{{.InterfaceName | lower}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: mocks
    interfaces:
      Client:
      Token:
  net:
    config:
      filename: "net_{{.InterfaceName | lower}}.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: mocks
    interfaces:
      Listener:
      Conn:
      Addr:
