# Example configuration for testing the HTTP API
log_level: info
min_record_length: 100
decrypt: true
inverter_type: "default"
timezone: "UTC"

server:
  host: "0.0.0.0"
  port: 5279

api:
  enabled: true
  host: "0.0.0.0"
  port: 8080

mqtt:
  enabled: false

pvoutput:
  enabled: false
